### ISSUE TITLE
Search existing projects - export functionality

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#502] opened 2019-01-09 20:39 UTC
There should be an export functionality for this screen. 

![image](https://user-images.githubusercontent.com/44984207/50927068-47567900-141c-11e9-82e2-dcf4d86c70ee.png)

**Comment by vbhat0891** [comment] 2019-03-20 22:08
Duplicate of  #764

**Closed** 2019-03-26 00:08 UTC
Labels: Group: Projects, enhancement
