### ISSUE TITLE
Change Footer

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#545] opened 2019-01-18 16:59 UTC
**(update first then check to make sure footer is working)**

- Exclude the “University Policies | Privacy Policy” links and just extend the horizontal line that is already there 
- Exclude the social media/media links and graphic indicators on the right
- Phone number should remain the same
- Using the discrimination statement that exists on the footer that needs to change – move the footer below the second horizontal white line and make the text much smaller (UCOMM will provide the gray text color for the footer)

New footer:
![uno footer](https://user-images.githubusercontent.com/44984230/51401013-69808300-1b0f-11e9-9e6d-c5c18f8f2a36.png)

_Originally posted by @robynlloos in https://github.com/uno-isqa-8950/uno-cpi/issue_comments#issuecomment-455614745_

**Comment by Keristiena** [comment] 2019-02-15 19:52
We have a new solution for contact us page.

**Comment by caadler** [comment] 2019-04-04 00:17
This is duplicate of #532.  Closing ticket.

**Closed** 2019-04-04 00:18 UTC
Labels: Accessibility/UI, UI
