### ISSUE TITLE
Project Form Fields

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#520] opened 2019-01-09 22:04 UTC
r Overall, the order of the fields when editing the project should be consistent with the project fields as they show in order and by display names within the actual project table. 

In addition to the above mentioned fields, others that are incorrectly named/ordered include:
•	Physical Address
•	City
•	State
•	Zip
•	Country

**Comment by Jantz021991** [comment] 2019-01-29 01:13
possible duplicate with 564 and 559

**Comment by vbhat0891** [comment] 2019-02-01 04:57
This is a duplicate of # 559, @Jantz021991 already worked on it.

**Closed by vbhat0891** 2019-02-01 04:57 UTC
Labels: Forms, Group: Projects, UI
